### ISSUE TITLE
Action - Assign Volunteers to Event

### ISSUE THREAD

**Issue by jhulen** [hack4impact-utk/rooted-east#15]
## Description
- This will go in the Events actions file
- You'll need to get the specific volunteer, which could be done by username or email, and this will be used to get the ID from the DB to add the volunteer to the event list.

## Dependencies

**Comment by amy-huang16** [comment]
Function takes in event and volunteer (either their email or something to get their ID), then add that ID to the list of volunteers for the event. Then add that event to the volunteer's list of events.
